### ISSUE TITLE
Error during insmod 

### ISSUE THREAD

**Issue by draugvar** [sysprogs/kgdboe#11]
On dmesg i see this error:
`kgdboe: this kernel version requires specifying the address of kallsyms_lookup_name explicitly. Please append 'kallsyms_lookup_name_address=0x...' to insmod command line.`
I'm not sure of what I'm supposed to do... How can I locate that address?

My linux version:
Linux ubuntu 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ashleysmithgpu** [comment]
@draugvar I managed to get it to work by doing:

```
$ sudo cat /proc/kallsyms | grep lookup_name
ffffffff9a94de00 T module_kallsyms_lookup_name
ffffffff9a94e3f0 T kallsyms_lookup_name
$ sudo insmod kgdboe.ko kallsyms_lookup_name_address=0xffffffff9a94e3f0
```

**Comment by draugvar** [comment]
Yes it worked! thanks :D
