### ISSUE TITLE
Potential to upstream

### ISSUE THREAD

**Issue by jhand2** [sysprogs/kgdboe#8]
I want to understand what is keeping this work from being upstreamed into the mainline kernel.

I did some digging and found it was proposed in patches many years ago but I couldn't find why it was never merged. Are the problems technical? Philosophical?

I think this module is great and it would be awesome if it could eventually be officially supported upstream. I would be interested in contributing to this effort if to limitation is just technical.

**Comment by sysprogs** [comment]
This is something to ask in the Kernel mailing lists. From our side, there are no objections if someone manages to integrate the module upstream, as long as they are willing to allocate their time addressing the feedback from the kernel maintainers and perform the necessary maintenance/bugfixing once the module is the part of the kernel.

**Comment by jhand2** [comment]
I am happy to work with maintainers to try to upstream this.

I was mostly curious about the history. That is, has someone tried to upstream this in the past and wasn't able for some reason? Or is it mostly an issue of not having the time?

**Comment by sysprogs** [comment]
On our side, this is purely a question of time. We have to focus on developing and supporting our paid products, such as [VisualKernel](https://sysprogs.com/VisualKernel/), hence the resources we can allocate to an auxiliary free tool such as **kgdboe** are extremely limited. If anyone else is willing to give it a try, we'll be more than happy to see it integrated in the kernel.

**Comment by disconnect3d** [comment]
@jhand2 Out of curiosity, after all this time, did you manage to do anything to upstream this or at least were there some discussions about kgdboe on the mailing lists?

**Comment by sysprogs** [comment]
@disconnect3d, it's a total speculation, but the network card driver maintainers may not like the additional work from keeping compatibility with KGDBoE, so they would want someone to commit to regularly testing it against newer kernel releases and many network drivers. It could be a tremendous amount of work for a fairly niche tool, so there may not be many volunteers willing to do so.

For what it's worth, we are introducing a better alternative to KGDBoE - [live kernel tracing](https://sysprogs.com/VisualKernel/tutorials/tracing/), that allows you to set tracepoints in arbitrary code locations, record values of arbitrary variables, and review or plot them later. Live tracing works by filling circular buffers when the tracepoints get hit, and reading them out via network, so it doesn't need any synchronization tricks like KGDBoE does, and works with any network driver regardless of how it's implemented.
